### ISSUE TITLE
Walkthroughs and Getting Started Guide

### ISSUE THREAD

**Issue by nikiforos-dev** [matrix-org/matrix-js-sdk#4250] opened 2024-06-18 04:14 UTC
Matrix team should consider making some basic walkthroughs (register user from scratch, create encrypted chat, etc.) there are plenty of multi stage workflows which are not straight forward concepts to glean from the API documentation.

**Comment by richvdh** [comment] 2024-06-26 16:13
duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/430

**Closed by richvdh** 2024-06-26 16:13 UTC
Labels: T-Other, A-Documentation
