### ISSUE TITLE
this.opts.request - NPE in http-api.js v20.1.0

### ISSUE THREAD

**Issue by san1t1** [matrix-org/matrix-js-sdk#2763] opened 2022-10-17 14:12 UTC
Just upgraded my Common JS project to the new version at 20.1.0

This code now fails:
```js
const client = matrix.createClient({ baseUrl: homeServerUrl });
const loginResult = await client.login('m.login.password', {
    user: this.#username,
    password: this.#password,
});
```
with 
```
 TypeError: this.opts.request is not a function

      233 |         try {
      234 |             const client = matrix.createClient({ baseUrl: homeServerUrl });
    > 235 |             const loginResult = await client.login('m.login.password', {
          |                                              ^
      236 |                 user: this.#username,
      237 |                 password: this.#password,
      238 |             });

      at MatrixHttpApi.doRequest (node_modules/matrix-js-sdk/src/http-api.ts:972:30)
      at MatrixHttpApi.callbacks [as requestOtherUrl] (node_modules/matrix-js-sdk/src/http-api.ts:838:29)
      at MatrixHttpApi.request (node_modules/matrix-js-sdk/lib/http-api.js:674:21)
      at MatrixHttpApi.authedRequest (node_modules/matrix-js-sdk/lib/http-api.js:608:37)
      at MatrixClient.authedRequest [as login] (node_modules/matrix-js-sdk/src/client.ts:7148:26)
      at MatrixUser.login (test/bridge/matrixClient.js:235:46)
      at login (test/bridge/util.js:53:18)
      at loginToMatrix (test/bridge/util.js:126:26)
      at Object.<anonymous> (test/bridge/processingUserMessages_test.js:105:24)
```

This is resolved by patching `http-api-js` line 851 from this:
```
            req = this.opts.request(
```
to this:
```
            req = this.opts.request.default(
```

I'm guessing this is going to be a packaging issue.

**Comment by t3chguy** [comment] 2022-10-17 14:14
Duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/2415

**Closed by t3chguy** 2022-10-17 14:14 UTC
