### ISSUE TITLE
Sometimes matrix js sdk will partially crash

### ISSUE THREAD

**Issue by Porianesu** [matrix-org/matrix-js-sdk#4433] opened 2024-09-26 10:43 UTC
Sometimes matrix js sdk will partially crash. At this point, some functions similar to queueToDevice will not be available and will report the error 'failed to exclude transaction'. When checking the console's IndexDB, it will be found that the entire crypto store database has disappeared, leaving only a name. But the sendMessage function can still be used, and the sent message can only be seen by oneself, not by the other party. Is there any way to detect this scene.

**Comment by richvdh** [comment] 2024-09-30 11:56
>  At this point, some functions similar to queueToDevice will not be available and will report the error 'failed to exclude transaction'

Failed to *exclude* transaction? Are you sure?

Could you paste the exact exception you are seeing?

**Comment by tiennguyen1293** [comment] 2024-11-27 02:06
look like i am facing the same issue, my log

```
[
IndexedDBStore failure, degrading to MemoryStore,

{
message: Cannot read properties of undefined (reading 'transaction'),
name: TypeError,
stack: 
TypeError: Cannot read properties of undefined (reading 'transaction')
    at https://app/static/js/8146.e1a0e198.js:2:7459211
    at g.promiseTry (https://app/static/js/8146.e1a0e198.js:2:7507690)
    at g.LocalIndexedDBStoreBackend.persistUserPresenceEvents (https://app/static/js/8146.e1a0e198.js:2:7459188)
    at g.LocalIndexedDBStoreBackend.doSyncToDatabase (https://app/static/js/8146.e1a0e198.js:2:7458507)
    at g.LocalIndexedDBStoreBackend.syncToDatabase (https://app/static/js/8146.e1a0e198.js:2:7458364)
    at a.<anonymous> (https://app/static/js/8146.e1a0e198.js:2:7465240)
    at a.reallySave (https://app/static/js/8146.e1a0e198.js:2:7467254)
    at a.save (https://app/static/js/8146.e1a0e198.js:2:7467057)
    at g.SyncApi.doSync (https://app/static/js/8146.e1a0e198.js:2:7493291)
}
]
```

![image](https://github.com/user-attachments/assets/b2383006-8aeb-4581-8382-d5087177c4e2)

**Comment by richvdh** [comment] 2024-11-27 10:22
@tiennguyen1293 I'm not sure if that is the same problem as the original reporter. Your stacktrace suggests that the indexeddb was closed for some reason (possibly another tab tried to upgrade it or delete it?). The code doesn't handle that situation elegantly, but the root cause is that closure. If you can provide more details, feel free to open another issue.

Given the lack of clarification from the original reporter, I'm going to go ahead and close this.

**Closed by richvdh** 2024-11-27 10:22 UTC
Labels: T-Defect, X-Needs-Info
