### ISSUE TITLE
get rooms with pagination ?

### ISSUE THREAD

**Issue by moeinrahimi** [matrix-org/matrix-js-sdk#936] opened 2019-06-03 07:22 UTC
is there any way to get a user rooms with pagination ?
there is this sync event but it has no limit for pagination so it's useless.

**Comment by turt2live** [comment] 2019-06-03 07:32
Duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/752

**Closed by turt2live** 2019-06-03 07:32 UTC
