### ISSUE TITLE
Replace deprecated "request"

### ISSUE THREAD

**Issue by guimard** [matrix-org/matrix-js-sdk#1392] opened 2020-06-01 12:44 UTC
Hi,

according to [upstream announce](https://github.com/request/request/issues/3142), `request` is deprecated and should be replaced by `got` or `axios`

**Comment by turt2live** [comment] 2020-06-01 13:19
Duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/801

**Closed by turt2live** 2020-06-01 13:19 UTC
