### ISSUE TITLE
Register new user for matrix.org using the SDK

### ISSUE THREAD

**Issue by nikiforos-dev** [matrix-org/matrix-js-sdk#4249] opened 2024-06-18 04:13 UTC
I would like to see an example of how to register a user on matrix.org from scratch.

**Comment by MidhunSureshR** [comment] 2024-06-19 07:56
Duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/4250

**Closed by MidhunSureshR** 2024-06-19 07:56 UTC
Labels: T-Other, A-Documentation
