### ISSUE TITLE
class heritage _events.EventEmitter is not an object or null

### ISSUE THREAD

**Issue by ralyodio** [matrix-org/matrix-js-sdk#2248] opened 2022-03-18 00:19 UTC
```
500

class heritage _events.EventEmitter is not an object or null

node_modules/matrix-js-sdk/lib/models/typed-event-emitter.js@http://localhost:3000/node_modules/.vite/matrix-js-sdk.js?v=5f51da5e:9813:29
__require@http://localhost:3000/node_modules/.vite/chunk-57B3GNUS.js?v=5f51da5e:24:50
node_modules/matrix-js-sdk/lib/models/user.js@http://localhost:3000/node_modules/.vite/matrix-js-sdk.js?v=5f51da5e:9868:30
__require@http://localhost:3000/node_modules/.vite/chunk-57B3GNUS.js?v=5f51da5e:24:50
node_modules/matrix-js-sdk/lib/store/memory.js@http://localhost:3000/node_modules/.vite/matrix-js-sdk.js?v=5f51da5e:11024:17
__require@http://localhost:3000/node_modules/.vite/chunk-57B3GNUS.js?v=5f51da5e:24:50
node_modules/matrix-js-sdk/lib/matrix.js@http://localhost:3000/node_modules/.vite/matrix-js-sdk.js?v=5f51da5e:41457:19
__require@http://localhost:3000/node_modules/.vite/chunk-57B3GNUS.js?v=5f51da5e:24:50
node_modules/matrix-js-sdk/lib/browser-index.js@http://localhost:3000/node_modules/.vite/matrix-js-sdk.js?v=5f51da5e:41979:44
__require@http://localhost:3000/node_modules/.vite/chunk-57B3GNUS.js?v=5f51da5e:24:50
@http://localhost:3000/node_modules/.vite/matrix-js-sdk.js?v=5f51da5e:42056:29
```

Trying to use with typescript and sveltekit and get the above erorr:

```
import * as sdk from 'matrix-js-sdk';

export const matrix = sdk.createClient('https://matrix.org');

```

```

<script>
	import { onMount } from 'svelte';
	import { matrix } from '$lib/chat.ts';

	onMount(() => {
		matrix.publicRooms(function (err, data) {
			console.log('Public Rooms: %s', JSON.stringify(data));
		});
	});
</script>
```

**Comment by t3chguy** [comment] 2022-03-21 09:14
Duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/1836 - you already commented on it, don't create duplicates.

**Closed by t3chguy** 2022-03-21 09:14 UTC
