### ISSUE TITLE
isLoggedIn returns false / isn't working correctly

### ISSUE THREAD

**Issue by KineticFox** [matrix-org/matrix-js-sdk#1453] opened 2020-08-30 21:06 UTC
const client = sdk.createClient('https: ...');
      client.login('m.login.password', {correct username & password}).then((res)) => {
        console.log(res.access_token); // im getting here the correct access token for my account
    });

the problem now is, if i call 

    client.isLoggedIn() 

the response is false?
what am i doing wrong or how i can recieve true

**Comment by t3chguy** [comment] 2020-08-30 22:47
After calling login you should construct a new client containing your new access_token for it to be logged in.

**Comment by turt2live** [comment] 2020-08-31 01:38
Duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/3#issuecomment-94496064

**Closed by turt2live** 2020-08-31 01:38 UTC
