### ISSUE TITLE
Can "request" be switched with, "node-fetch" within this sdk?

### ISSUE THREAD

**Issue by tearfulnumpty** [matrix-org/matrix-js-sdk#2570] opened 2022-08-07 22:45 UTC
**Is your feature request related to a problem? Please describe.**
The [request npm package is deprecated](https://www.npmjs.com/package/request) as of ~two years ago.  It is used in the matrix-js-sdk for [various workarounds.](https://github.com/matrix-org/matrix-js-sdk/issues/2415#issuecomment-1141246410)  

**Describe the solution you'd like**
A swap of "request" over to "node-fetch" would be great for a workaround to the above problem #2415 

**Describe alternatives you've considered**
In place of matrix-js-sdk relying on node-fetch, if it was possible to avoid the above error from #2415 without using request, this could be a valid solution depending on the exact solution found.

**Additional context**
Work is being done to create a matrix plugin for the [Shinobi CCTV](https://shinobi.video/) NVR software project.  Notifications from events (such as motion detection on a security camera) are to be sent to a Matrix server from Shinobi, using [the matrix-js-sdk as a sort of, "plugin" for Shinobi](https://gitlab.com/Shinobi-Systems/Shinobi/-/blob/matrix-notifications/libs/notifications/matrix.js).  The error mentioned above at #2415 appears without the added workaround in place.  Due to the deprecated status of the request package, the developer of Shinobi would like to avoid using it in favor of the node-fetch package.  

___

Thanks for your time!  I appreciate it a lot.

**Comment by moeiscool** [comment] 2022-08-07 22:57
I second this, I would really like to include Matrix Notifications in Shinobi but cannot unless request is removed :( Thank you for considering this change.

**Comment by t3chguy** [comment] 2022-08-08 08:53
Duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/801

**Closed by t3chguy** 2022-08-08 08:53 UTC
