### ISSUE TITLE
More information about general concepts needed

### ISSUE THREAD

**Issue by niwla23** [matrix-org/matrix-js-sdk#1607] opened 2021-02-17 23:13 UTC
The documentation is very technical, there is no info about how this is supposed to work alltogether.

What is the difference between a Store and a Crypto Store? What is the prefered store? How should you persist the session? I tried with IndexedDBStore and it doesn't automatically re-login.

Can someone answer these questions and / or maybe improve the home page with a little more realistic examples? I am trying to build a client in Vue.js

**Comment by niwla23** [comment] 2021-02-18 00:07
#1608 

My questions where answered here.

I think it would be a good idea to put the info, that a store is not storing credentials but rooms and such stuff and you should store the access token on the application layer. And the fact you only need cryptostore if you use e2e could also be highlighted better.

**Comment by jryans** [comment] 2021-02-27 15:09
A lot of work is needed to make the documentation more approachable, yes.

**Comment by tawandamoyo** [comment] 2021-11-06 18:14
I would like to help out here, I like writing. Where can I start?

**Comment by richvdh** [comment] 2024-06-26 16:14
duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/430

**Closed by richvdh** 2024-06-26 16:14 UTC
Labels: A-Documentation
