### ISSUE TITLE
Pushrules with Dotted Value keys break

### ISSUE THREAD

**Issue by schmop** [matrix-org/matrix-js-sdk#1454] opened 2020-08-31 11:15 UTC
I wanted to configure a pushrule ignoring "m.replace" events.
Therefore i used this configuration:

```
{
    scope: 'global',
    kind: 'override',
    ruleId: 'rule.no_edits',
    body: {
        actions: [
            'dont_notify'
        ],
        conditions: [
            {
                'kind': 'event_match',
                'key': 'type',
                'pattern': 'm.room.message'
            },
            {
                'kind': 'event_match',
                'key': 'content.m.relates_to.rel_type',
                'pattern': 'm.replace'
            },
        ]
    },
}
```

But the behaviour of Synapse and the matrix-js-sdk didn't match.
The condition key `content.m.relates_to.rel_type` is interpreted in the valueDottedForKey method wrong:

Actual part splitting:
`['content', 'm', 'relates_to', 'rel_type']` 
Needed splitting:
`['content', 'm.relates_to', 'rel_type']`

https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/pushprocessor.js#L292
```
        const parts = key.split('.');
```

Maybe the approach of just splitting by the dot is undesirable.
Synapse takes the apporach the other way around, converting the nested object to a flat object and afterwards just accessing by the key.

Pseudo:
```js
function accessDottedKey(evt, key) {
   flatEvt = makeFlat(evt);
   return flatEvt[key];
}
```

**Comment by turt2live** [comment] 2020-08-31 13:00
This is a feature of the spec.

**Comment by schmop** [comment] 2020-08-31 13:32
Under https://matrix.org/docs/spec/client_server/latest#conditions i only see that key is defined as a
> key: The dot-separated field of the event to match, e.g. content.body

How can the feature of the spec result in inconsistent behaviour over server (synapse) and client (matrix-js-sdk)?
This bug renders fields in events, that contain dots (like 'm.relates_to') non-referencable.
Or does it mean, that synapse has the bug here, because synapse IMO correctly supresses the push notification, but the matrix-js-sdk does not.

**Comment by turt2live** [comment] 2020-08-31 13:34
it would be a synapse bug, though would likely get redirected to the spec to be fixed via an MSC

**Comment by t3chguy** [comment] 2020-09-01 08:12
This doesn't sound like a Synapse bug as per https://github.com/matrix-org/matrix-doc/issues/2641#issuecomment-645275547

It sounds like a js-sdk pushprocessor.js bug if it is relating to encrypted rooms.

**Comment by turt2live** [comment] 2020-09-01 12:48
Synapse is off-spec though?

**Comment by t3chguy** [comment] 2020-09-01 12:50
Based on https://github.com/matrix-org/matrix-doc/issues/2641 saying

> It's unclear how these are handled.

I'd say neither are incorrect and the spec needs clarification/changing

**Comment by turt2live** [comment] 2020-09-01 12:52
The spec is fairly clear on what to do, and the issue is categorized as a wart rather than a bug. All this means is that it needs an MSC, but until then it's something we live with.

**Closed** 2020-09-01 13:00 UTC
