### ISSUE TITLE
Caught /sync error

### ISSUE THREAD

**Issue by drale2k** [matrix-org/matrix-js-sdk#1371] opened 2020-05-10 21:16 UTC
Version v6.0.0 using https://github.com/matrix-org/matrix-js-sdk/releases/download/v6.0.0/browser-matrix.js

Getting the following error

```
[Error] Caught /sync error (1)

removeHiddenChars — utils.ts:659
_updateDisplayNameCache — room-state.js:756
(anonymous function) — room-state.js:312
forEach — utils.ts:139
(anonymous function) — room-state.js:301
(anonymous function) — event-timeline.js:105
(anonymous function) — sync.js:1589
_callee9$ — sync.js:1240
tryCatch — runtime.js:45
invoke — runtime.js:274
asyncGeneratorStep — asyncToGenerator.js:3
_next — asyncToGenerator.js:25
(anonymous function) — asyncToGenerator.js:32
Promise
(anonymous function) — asyncToGenerator.js:21
(anonymous function) — utils.ts:731
generatorResume
fulfilled — utils.ts:16
promiseReactionJob
_callee7$ (browser-matrix.js:63870)
tryCatch (browser-matrix.js:5787)
invoke (browser-matrix.js:6016)
asyncGeneratorStep (browser-matrix.js:40)
_throw (browser-matrix.js:66)
promiseReactionJob
```

**Comment by drale2k** [comment] 2020-05-10 22:32
I was able to fix this by making the follow change to `brower-matrix.js`

Line 66094-66096 - Removing the call to **.default**

From
```
function removeHiddenChars(str) {
    return unhomoglyph_1.default(str.normalize('NFD').replace(removeHiddenCharsRegex, ''));
}
```

To
From
```
function removeHiddenChars(str) {
    return unhomoglyph_1(str.normalize('NFD').replace(removeHiddenCharsRegex, ''));
}
```

**Comment by turt2live** [comment] 2020-05-11 15:41
Duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/1216

**Closed by turt2live** 2020-05-11 15:41 UTC
