### ISSUE TITLE
Add guide how to use this package

### ISSUE THREAD

**Issue by vitonsky** [matrix-org/matrix-js-sdk#4194] opened 2024-05-07 21:43 UTC
Hi, I tried to use this library, but it is absolutely not possible with no any guideline.

Currently i can found only generated SDK API http://matrix-org.github.io/matrix-js-sdk/ that is pretty useless, because does not explain any concepts, any high level library design and does not provide any information about typical use cases.

I tried to implement a trivial scenario where a bot automatically join to any chat and respond with echo. But i have a lot of problems and questions like
- how i can get messages? okay, it looks i have to listen events and filter it by type `m.room.message`
- why i don't see any messages? I know that i sent it to bot. Ohh, okay, it looks this SDK can't decrypt it, it make sense, how i can setup cryptography?
- okay, I've installed `olm` and i do `(global as any).Olm = olm.default` which is pretty bad design, but how I can setup cryptography from my recovery key?

Finally, i decided to pause my exploration of this SDK, because it have a pretty low quality due to lack of documentation.

Could you provide some guide with:
- SDK high level design explanation
- trivial examples, like "echo client that join invites and answer to ecnrypted messages"

**Comment by harrismcc** [comment] 2024-05-22 01:18
This would be huge. I'm in the same boat, where even a simple example (that isn't super out of date) would be helpful. There seems to be a ton of ways to do the same things and it's not clear as a consumer of this SDK what the intended way is.

I would be happy to help contribute to this, although I'd need to understand it myself first!

**Comment by nukeop** [comment] 2024-06-09 18:47
They've got some examples here:

- https://github.com/matrix-org/matrix-js-sdk/blob/master/examples/node/app.js
- https://matrix.org/docs/older/usage-of-the-matrix-js-sdk/

**Comment by nikiforos-dev** [comment] 2024-06-18 04:16
yeah but they are not easy to understand at all. You need a PHD in matrix before you can do anything basic. Creating and interacting with rooms is straight forward, but if you want to encrypt the chat, createa a new user, invite new users, it's basically a month long mystery to find out how. The docs are not good. They are too atomic and need to be fit into the context of real-world use-cases.

**Comment by nukeop** [comment] 2024-06-18 07:06
That is true but you can easily implement those methods behind a simple api yourself and then use that. Discord makes that a lot easier admittedly.

**Comment by richvdh** [comment] 2024-06-26 16:12
duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/430

**Closed by richvdh** 2024-06-26 16:12 UTC
Labels: T-Other, A-Documentation
