### ISSUE TITLE
Registration Example

### ISSUE THREAD

**Issue by nikiforos-dev** [matrix-org/matrix-js-sdk#4248] opened 2024-06-18 02:32 UTC
Can someone please provide a registration walk-through example for matrix.org? It uses recaptcha, email, and terms as stages. I can use this sdk for chat room operations, but I can't figure out how to use it for the registration flow. At least if someone can point me to the method to use that be a big help.

**Comment by MidhunSureshR** [comment] 2024-06-19 08:01
Duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/4250

Please stop creating multiple issues. You should read the [spec](https://spec.matrix.org/latest/client-server-api/#account-registration-and-management) and see how matrix-react-sdk uses the sdk for the same.

**Closed by MidhunSureshR** 2024-06-19 08:01 UTC
Labels: T-Other, A-Documentation
