### ISSUE TITLE
Types declarations don't work

### ISSUE THREAD

**Issue by andrevmatos** [matrix-org/matrix-js-sdk#1769] opened 2021-07-05 22:31 UTC
**Describe the bug**
While trying to remove our usage of `@types/matrix-js-sdk` and replace it with the natively generated types in v12 (https://github.com/raiden-network/light-client/pull/2846), we stumbled upon some issues:
- First, we had to add `"noImplicitAny": false` to our `tsconfig.json` in order for `tsc` to not complain about the several places where `matrix-js-sdk` types import from untyped `.js` files in the output; this forces us to lower our type strictness if we want to use your types; ideally, `matrix-js-sdk` should at least add empty `declare module` entries for the modules still not converted to `.ts`, so projects using it would build cleanly and not need to loosen its configs
- `lib/crypto/CrossSigning.d.ts` uses `PkSigning` type from `@matrix-org/olm`, which is declared as a **devDependency** and therefore not installed when installing `matrix-js-sdk` as a dependency. For **any** lib where types are needed by the emitted declarations, you must either `declare module` it somewhere accessible or move this to runtime `dependencies` to allow other projects to build cleanly
- `store/memory.ts` and `store/sub.ts` wrongly implement `IStore`: the formers's `getAccountData` return type `MatrixEvent | undefined` is not assignable to interface's return type `MatrixEvent`. `undefined` needs to be added to `IStore.getAccountData`'s returned type
- `webrtc/call.ts` uses `DesktopCapturerSource` types, which are declared in `@types/global.d.ts` and **not** copied to `lib`. [It seems you may need an additional post-build step](https://stackoverflow.com/a/56440335/1895161) to ensure `.d.ts` files are properly exposed in your `lib` build folder

**To Reproduce**
1. Have a TS project using `matrix-js-sdk`
2. Try to build such project out-of-the-box

**Expected behavior**
The project can cleanly build with the provided types

**Additional context**
Our current `tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ES2020",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "strict": true,
    "sourceMap": true,
    "declaration": true,
    "pretty": true,
    "lib": ["ES2020", "dom"],
    "outDir": "./dist/"
  },
  "include": ["./src/**/*.ts"]
}
```

**Comment by andrevmatos** [comment] 2021-07-05 22:32
The build of a project using `matrix-js-sdk` currently looks like this:
```
$ tsc
^[../node_modules/matrix-js-sdk/lib/crypto/CrossSigning.d.ts:7:27 - error TS2307: Cannot find module '@matrix-org/olm' or its corresponding type declarations.

7 import { PkSigning } from "@matrix-org/olm";
                            ~~~~~~~~~~~~~~~~~

../node_modules/matrix-js-sdk/lib/store/memory.d.ts:164:5 - error TS2416: Property 'getAccountData' in type 'MemoryStore' is not assignable to the same property in base type 'IStore'.
  Type '(eventType: string) => MatrixEvent | undefined' is not assignable to type '(eventType: string) => MatrixEvent'.
    Type 'MatrixEvent | undefined' is not assignable to type 'MatrixEvent'.
      Type 'undefined' is not assignable to type 'MatrixEvent'.

164     getAccountData(eventType: EventType | string): MatrixEvent | undefined;
        ~~~~~~~~~~~~~~

../node_modules/matrix-js-sdk/lib/store/stub.d.ts:137:5 - error TS2416: Property 'getAccountData' in type 'StubStore' is not assignable to the same property in base type 'IStore'.
  Type '(eventType: string) => MatrixEvent | undefined' is not assignable to type '(eventType: string) => MatrixEvent'.
    Type 'MatrixEvent | undefined' is not assignable to type 'MatrixEvent'.
      Type 'undefined' is not assignable to type 'MatrixEvent'.

137     getAccountData(eventType: EventType | string): MatrixEvent | undefined;
        ~~~~~~~~~~~~~~

../node_modules/matrix-js-sdk/lib/webrtc/call.d.ts:138:68 - error TS2304: Cannot find name 'DesktopCapturerSource'.

138 export declare function getDesktopCapturerSources(): Promise<Array<DesktopCapturerSource>>;
                                                                       ~~~~~~~~~~~~~~~~~~~~~

../node_modules/matrix-js-sdk/lib/webrtc/call.d.ts:207:72 - error TS2304: Cannot find name 'DesktopCapturerSource'.

207     placeScreenSharingCall(selectDesktopCapturerSource?: () => Promise<DesktopCapturerSource>): Promise<void>;
                                                                           ~~~~~~~~~~~~~~~~~~~~~


Found 5 errors.

error Command failed with exit code 2.
```

**Comment by SimonBrandner** [comment] 2021-07-06 05:21
This looks like a duplicate of https://github.com/matrix-org/matrix-js-sdk/issues/1645, at least partially

**Comment by laurensiusadi** [comment] 2021-07-17 10:53
You can try using https://github.com/Jack-Works/matrix-js-sdk-type (install with the git url)
It works great for me.

**Comment by t3chguy** [comment] 2022-11-03 16:10
This library now conforms to `tsc` `strict` which includes noImplicitAny

**Closed by t3chguy** 2022-11-03 16:10 UTC
